[tool.poetry]
name = "openwrt-composer"
version = "0.1.0"
description = "An OpenWRT firmware builder which takes input from a YAML manifest"
authors = ["Jonathan G. Underwood <jonathan.underwood@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
"ruamel.yaml" = "^0.16.10"
click-log = "^0.3.2"
requests = "^2.23.0"
netjsonconfig = "^0.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
tox = "^3.14.6"
flake8 = "^3.7.9"

[tool.poetry.scripts]
owc = 'openwrt_composer.main:build'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

